modLoader="lowcodefml"
loaderVersion="[40,]"
license="MIT license"

[[mods]]
modId="futurepack_additions"
version="1.1"
displayName="Futurepack Additions"
logoFile="pack.png"
authors="Xia_Xin,YuapixN"

[dependencies]
[[dependencies.futurepack_additions]]
modId = "forge"
mandatory = true
versionRange = "[40,]"
ordering = "NONE"
side = "BOTH"

[[dependencies.futurepack_additions]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2]"
ordering = "NONE"
side = "BOTH"
