modLoader="lowcodefml"
loaderVersion="[40]"
license="MIT license"

[[mods]]
modId="futurepack_additions"
version="1.0"
displayName="Futurepack Additions"
logoFile="pack.png"
authors="Xia_Xin,YuapixN"

[[dependencies.futurepack_additions]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"
